// Generated by CoffeeScript 1.8.0
(function() {
  this.config = {
    templateBaseUrl: '/views/',
    useHtml5Mode: false,
    projectSheetTemplateSlug: 'unisson',
    defaultSiteTags: ['lille'],
    editorialSuggestedTags: [],
    defaultResultLimit: 28,
    bucket_uri: 'http://data.patapouf.org/bucket/upload/',
    loginBaseUrl: 'http://data.patapouf.org/api/v0',
    oauthBaseUrl: 'http://lille.encommuns.org',
    oauthCliendId: '1yyK2QCNeuxat4jEhDTricCPGAlY6Fipt3WBc64B',
    media_uri: 'http://data.patapouf.org',
    rest_uri: "http://data.patapouf.org/api/v0",
    dataserver_url: "http://data.patapouf.org"
  };

}).call(this);
