// Generated by CoffeeScript 1.8.0
(function() {
  var CurrentProfileService, module;

  module = angular.module("commons.accounts.services", ['restangular']);

  module.factory('User', function(Restangular) {
    return Restangular.service('account/user');
  });

  module.factory('Profile', function(Restangular) {
    return Restangular.service('account/profile');
  });

  module.factory('ObjectProfileLink', function(Restangular) {
    return Restangular.service('objectprofilelink');
  });

  CurrentProfileService = (function() {
    function CurrentProfileService($rootScope, $modal, Profile) {
      console.log(" Init CurrentProfileService ");
      if ($rootScope.authVars.isAuthenticated) {
        $rootScope.currentProfile = Profile.one().get({
          'user__username': $rootScope.authVars.username
        }).$object;
        console.log(" Current profile ", $rootScope.currentProfile);
      }
      $rootScope.openSignupPopup = function() {
        var modalInstance;
        return modalInstance = $modal.open({
          templateUrl: 'views/base/signupModal.html',
          controller: 'SignupPopupCtrl'
        });
      };
      $rootScope.openSigninPopup = function() {
        var modalInstance;
        $rootScope.authVars.loginrequired = true;
        return modalInstance = $modal.open({
          templateUrl: 'views/base/signinModal.html',
          controller: 'SigninPopupCtrl'
        });
      };
      $rootScope.$watch('authVars.username', function(newValue, oldValue) {
        if ((newValue !== oldValue) && (newValue !== '')) {
          return $rootScope.currentProfile = Profile.one().get({
            'user__username': newValue
          }).$object;
        }
      });
    }

    return CurrentProfileService;

  })();

  module.factory('CurrentProfileService', function($rootScope, $modal, Profile) {
    return new CurrentProfileService($rootScope, $modal, Profile);
  });

  module.controller('SignupPopupCtrl', function($scope, $rootScope, $modalInstance, $state, User) {
    "Controller bound to openSignupPopup method of CurrentProfile service";
    return $scope.register = function() {
      $scope.user.email = $scope.user.username;
      return User.post($scope.user).then(function(userResult) {
        $rootScope.authVars.username = $scope.user.username;
        $rootScope.authVars.password = $scope.user.password;
        $rootScope.loginService.submit();
        return $modalInstance.close();
      });
    };
  });

  module.controller('SigninPopupCtrl', function($scope, $rootScope, $modalInstance, $state, User) {
    "Controller bound to openSigninPopup method of CurrentProfile service";
    console.log(" init signin ctrler");
    return $rootScope.$watch('authVars.isAuthenticated', function(newValue, oldValue) {
      console.log(" isAuthenticated ? ", newValue);
      if (newValue === true) {
        return $modalInstance.close();
      }
    });
  });

}).call(this);
