// Generated by CoffeeScript 1.8.0
(function() {
  var module;

  module = angular.module('commons.encommuns.services', ['restangular']);

  module.factory('Usages', function(Restangular) {
    return Restangular.service('project/commons/usage?limit=300');
  });

  module.factory('OneUsage', function(Restangular) {
    return Restangular.service('project/commons/usage');
  });

  module.factory('Projects', function(Restangular) {
    return Restangular.service('project/project');
  });

  module.factory('Pertinences', function(Restangular) {
    return Restangular.service('project/commons/pertinence?limit=2000');
  });

  module.factory('OnePertinence', function(Restangular) {
    return Restangular.service('project/commons/pertinence');
  });

  module.factory('Prestations', function(Restangular) {
    return Restangular.service('project/commons/prestation');
  });

  module.factory('ProjectTools', function(Restangular) {
    return Restangular.service('project/tool');
  });

  module.factory('EvaluationIngredient', function(Restangular) {
    return Restangular.service('unisson/evaluation');
  });

  module.factory('HelpfulTips', function(Restangular) {
    return Restangular.service('unisson/ingredient');
  });

}).call(this);
