// Generated by CoffeeScript 1.8.0
(function() {
  var module;

  module = angular.module("commons.catalog.services", ['restangular']);

  module.factory('Project', function(Restangular) {
    return Restangular.service('project/project');
  });

  module.factory('ProjectSheet', function(Restangular) {
    return Restangular.service('project/sheet/projectsheet');
  });

  module.factory('PostalAddress', function(Restangular) {
    return Restangular.service('scout/postaladdress');
  });

  module.factory('ProjectSheetTemplate', function(Restangular) {
    return Restangular.service('project/sheet/template');
  });

  module.factory('ProjectSheetQuestionAnswer', function(Restangular) {
    return Restangular.service('project/sheet/question_answer');
  });

  module.factory('ProjectProgress', function(Restangular) {
    return Restangular.service('projectprogress');
  });

  module.factory('BucketFile', function(Restangular) {
    return Restangular.service('bucket/file');
  });

  module.factory('Bucket', function(Restangular) {
    return Restangular.service('bucket/bucket');
  });

  module.factory('PostalAddress', function(Restangular) {
    return Restangular.service('scout/postaladdress');
  });

  module.factory('BareRestangular', function(Restangular) {
    return Restangular.withConfig(function(RestangularConfigurer) {
      return RestangularConfigurer.setBaseUrl(config.dataserver_url);
    });
  });

}).call(this);
