// Generated by CoffeeScript 1.8.0
(function() {
  var module;

  module = angular.module('commons.base.filters', []);

  module.filter('tagFieldNotInArray', function() {
    "Filter out items whose field \"fieldName\" is contained within a given \"array\"";
    return function(items, array, fieldName) {
      var filtered;
      filtered = _.reject(items, function(item) {
        return _.contains(array, item[fieldName]);
      });
      return filtered;
    };
  });

}).call(this);
